version: 2.1

jobs:
    test:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout
            - run:
                  name: install packages
                  command: npm install

workflows:
    orb-free-workflow:
        jobs:
            - test
p